import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BgImages from "@components/layout/background/BgImages";
import Blur from "@components/layout/background/Blur";
import TopNavbarDesktop from "@components/layout/navbar/TopNavbarDesktop";
import TopNavbarPhone from "@components/layout/navbar/TopNavbarPhone";
import RightNavbar from "@components/layout/navbar/RightNavbar";
import Client from "@components/layout/Client";
import LazyMotionClient from "@components/layout/LazyMotionClient";

export const metadata: Metadata = {
  title: "Zeyad Saeed",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Blur />
        <BgImages />
        <LazyMotionClient>
          <TopNavbarDesktop />
          <TopNavbarPhone />
          <RightNavbar />
          <Client>{children}</Client>
        </LazyMotionClient>
      </body>
    </html>
  );
}
